# -*- coding: utf-8 -*-
"""święty mikołaj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A1ng0Gz_UbGMW7wh8NZO0rSmti00cqJ-
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np # Użycie plt.np.random zostało zastąpione na np.random dla pewności

def draw_christmas_scene():
    """Rysuje scenę z Mikołajem i choinką za pomocą Matplotlib."""

    st.title('Święty Mikołaj w Świątecznej Scenerii 🎄')
    st.write('Wygenerowany obraz za pomocą Matplotlib w Streamlit.')

    plt.figure(figsize=(10, 10))
    ax = plt.gca()

    # --- Tło (Śnieżna Noc) ---
    ax.add_patch(patches.Rectangle((-5, -5), 10, 10, color='#2F4F4F')) # Ciemne niebo
    ax.add_patch(patches.Rectangle((-5, -5), 10, 4, color='white')) # Ośnieżony grunt

    # Gwiazdy
    for _ in range(50):
        # Zmieniono na np.random, aby było spójne
        ax.add_patch(patches.Circle(
            (np.random.uniform(-5, 5), np.random.uniform(0, 5)),
            0.05,
            color='white',
            alpha=np.random.uniform(0.3, 1.0)
        ))

    # --- Święty Mikołaj ---

    # Ciało (czerwony strój)
    body_oval = patches.Ellipse((0, -0.6), 1.3, 1.5, color='red')
    ax.add_patch(body_oval)

    # Głowa (kolor skóry)
    head_circle = patches.Circle((0, 0.7), 0.35, color='#FAD0C4')
    ax.add_patch(head_circle)

    # Czapka (czerwona, bardziej szpiczasta)
    hat_base = patches.Rectangle((-0.4, 0.9), 0.8, 0.3, color='red')
    ax.add_patch(hat_base)
    hat_tip = patches.Polygon([(-0.4, 1.2), (0.4, 1.2), (0.0, 1.9)], color='red')
    ax.add_patch(hat_tip)

    # Obszycie czapki (białe)
    ax.add_patch(patches.Ellipse((0, 0.9), 0.9, 0.2, color='white', angle=0))

    # Pompon na czapce (biały)
    pom_pom = patches.Circle((0.0, 1.9), 0.12, color='white')
    ax.add_patch(pom_pom)

    # Broda (biała, pełniejsza)
    beard_body = patches.Ellipse((0, 0.0), 1.2, 1.0, color='white', angle=0, alpha=0.9)
    ax.add_patch(beard_body)
    beard_lower = patches.Polygon([(-0.6, 0.0), (0.0, -0.5), (0.6, 0.0)], color='white')
    ax.add_patch(beard_lower)

    # Wąsy (białe)
    ax.add_patch(patches.Ellipse((-0.2, 0.5), 0.3, 0.15, color='white', angle=20))
    ax.add_patch(patches.Ellipse((0.2, 0.5), 0.3, 0.15, color='white', angle=-20))

    # Oczy (czarne)
    eyes_left = patches.Circle((-0.18, 0.8), 0.05, color='black')
    eyes_right = patches.Circle((0.18, 0.8), 0.05, color='black')
    ax.add_patch(eyes_left)
    ax.add_patch(eyes_right)

    # Nos (czerwony, wydatny)
    nose = patches.Circle((0, 0.6), 0.09, color='red')
    ax.add_patch(nose)

    # Pasek (czarny)
    belt = patches.Rectangle((-0.6, -1.0), 1.2, 0.2, color='black')
    ax.add_patch(belt)

    # Klamra paska (złoty kwadrat)
    buckle = patches.Rectangle((-0.2, -1.05), 0.4, 0.3, color='gold')
    ax.add_patch(buckle)

    # Ramiona (czerwony strój, bliżej ciała)
    arm_width = 0.4
    arm_height = 0.7
    arm_left = patches.Rectangle((-0.9, -0.8), arm_width, arm_height, angle=10, color='red')
    arm_right = patches.Rectangle((0.5, -0.8), arm_width, arm_height, angle=-10, color='red')
    ax.add_patch(arm_left)
    ax.add_patch(arm_right)

    # Dłonie (białe rękawiczki)
    hand_radius = 0.2
    # Skorygowane pozycje rąk dla lepszego dopasowania
    hand_left = patches.Circle((-0.9 + arm_width/2, -0.8 + arm_height/2 - 0.2), hand_radius, color='white')
    hand_right = patches.Circle((0.5 + arm_width/2, -0.8 + arm_height/2 - 0.2), hand_radius, color='white')
    ax.add_patch(hand_left)
    ax.add_patch(hand_right)

    # Nogi (czerwony strój)
    leg_width = 0.3
    leg_height = 0.7
    leg_left = patches.Rectangle((-0.4, -1.7), leg_width, leg_height, color='red')
    leg_right = patches.Rectangle((0.1, -1.7), leg_width, leg_height, color='red')
    ax.add_patch(leg_left)
    ax.add_patch(leg_right)

    # Buty (czarne)
    boot_width = 0.4
    boot_height = 0.25
    boot_left = patches.Rectangle((-0.45, -1.95), boot_width, boot_height, color='black')
    boot_right = patches.Rectangle((0.05, -1.95), boot_width, boot_height, color='black')
    ax.add_patch(boot_left)
    ax.add_patch(boot_right)

    # --- Choinka (Szczegółowa) ---
    tree_x_pos = -3.0
    tree_y_pos = -1.5

    # Pień
    ax.add_patch(patches.Rectangle((tree_x_pos - 0.2, tree_y_pos - 0.5), 0.4, 0.7, color='saddlebrown'))

    # Warstwy igliwia
    ax.add_patch(patches.Polygon([
        (tree_x_pos, tree_y_pos + 2.5),
        (tree_x_pos - 1.2, tree_y_pos + 1.0),
        (tree_x_pos + 1.2, tree_y_pos + 1.0)
    ], color='forestgreen'))
    ax.add_patch(patches.Polygon([
        (tree_x_pos, tree_y_pos + 1.5),
        (tree_x_pos - 0.9, tree_y_pos + 0.0),
        (tree_x_pos + 0.9, tree_y_pos + 0.0)
    ], color='forestgreen'))
    ax.add_patch(patches.Polygon([
        (tree_x_pos, tree_y_pos + 0.5),
        (tree_x_pos - 0.6, tree_y_pos - 1.0),
        (tree_x_pos + 0.6, tree_y_pos - 1.0)
    ], color='forestgreen'))

    # Gwiazda na czubku
    ax.add_patch(patches.RegularPolygon((tree_x_pos, tree_y_pos + 2.7), numVertices=5, radius=0.2, orientation=0, color='gold', edgecolor='orange', linewidth=0.5))

    # Bombki
    ornaments_tree = [
        (tree_x_pos - 0.8, tree_y_pos + 1.8, 'red'),
        (tree_x_pos + 0.7, tree_y_pos + 1.6, 'blue'),
        (tree_x_pos - 0.4, tree_y_pos + 0.8, 'gold'),
        (tree_x_pos + 0.5, tree_y_pos + 0.5, 'purple'),
        (tree_x_pos - 0.2, tree_y_pos - 0.2, 'orange'),
        (tree_x_pos + 0.3, tree_y_pos - 0.7, 'red')
    ]
    for ox, oy, ocolor in ornaments_tree:
        ax.add_patch(patches.Circle((ox, oy), 0.08, color=ocolor, edgecolor='black', linewidth=0.5))

    # --- Prezenty obok choinki ---
    present1_x = tree_x_pos - 1.0
    present1_y = tree_y_pos - 1.0
    ax.add_patch(patches.Rectangle((present1_x, present1_y), 0.6, 0.6, color='darkred', edgecolor='black', linewidth=0.5))
    ax.add_patch(patches.Rectangle((present1_x + 0.25, present1_y), 0.1, 0.6, color='gold'))
    ax.add_patch(patches.Rectangle((present1_x, present1_y + 0.25), 0.6, 0.1, color='gold'))

    present2_x = tree_x_pos + 0.4
    present2_y = tree_y_pos - 1.2
    ax.add_patch(patches.Rectangle((present2_x, present2_y), 0.7, 0.7, color='navy', edgecolor='black', linewidth=0.5))
    ax.add_patch(patches.Rectangle((present2_x + 0.3, present2_y), 0.1, 0.7, color='silver'))
    ax.add_patch(patches.Rectangle((present2_x, present2_y + 0.3, ), 0.7, 0.1, color='silver'))

    # Ustawienie proporcji i wyłączenie osi
    plt.axis('equal')
    plt.axis('off')
    plt.title('Święty Mikołaj z Blisko Ułożonymi Rękami, Choinką i Prezentami')

    # Wyświetlenie wykresu w Streamlit
    st.pyplot(plt)

if __name__ == "__main__":
    draw_christmas_scene()